myshop/cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.cart_detail, name='cart_detail'),
	url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
	url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

myshop/myshop/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
	url(r'^cart/', include('cart.urls', namespace='cart')),
	url(r'^', include ('shop.urls', namespace='shop')),
]
if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myshop/shop/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [ 
	url(r'^$', views.product_list, name='product_list'),
	#url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
	url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
	url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
	url(r'^(?P<category_slug>[-\w]+)/(?P<subcategory_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
	url(r'^(?P<category_slug>[-\w]+)/(?P<subcategory_slug>[-\w]+)/(?P<subsubcategory_slug>[-\w]+)$', views.product_list, name='product_list_by_category'),
]

myshop/cart/models.py
from django.db import models

# Create your models here.

myshop/shop/models.py
from django.db import models
from django.core.urlresolvers import reverse

class Category(models.Model):
	name = models.CharField(max_length=200, db_index=True)
	slug = models.SlugField(max_length=200, db_index=True,unique=True)
	class Meta:
		ordering = ('name',)
		verbose_name = 'category'
		verbose_name_plural = 'categories'
	def __str__(self):
		return self.name
	def get_absolute_url(self):
		return reverse('shop:product_list_by_category', args=[self.slug])
	
class SubCategory(models.Model):
	category = models.ForeignKey(Category,related_name='category')
	name = models.CharField(max_length=200, db_index=True)
	slug = models.SlugField(max_length=200, db_index=True,unique=True)
	class Meta:
		ordering = ('name',)
		verbose_name = 'subcategory'
		verbose_name_plural = 'subcategories'
	def __str__(self):
		return self.name
	def get_absolute_url(self):
		return reverse('shop:product_list_by_category' ,args=[self.category.slug, self.slug])
	
class SubSubCategory(models.Model):
	subcategory = models.ForeignKey(SubCategory,related_name='subcategory')
	name = models.CharField(max_length=200, db_index=True)
	slug = models.SlugField(max_length=200, db_index=True,unique=True)
	class Meta:
		ordering = ('name',)
		verbose_name = 'subsubcategory'
		verbose_name_plural = 'subsubcategories'
	def __str__(self):
		return self.name
	def get_absolute_url(self):
		return reverse('shop:product_list_by_category', args=[self.subcategory.category.slug, self.subcategory.slug ,self.slug])
	#w adminie kategoria jest opcjonalna
	
class Product(models.Model):
	category = models.ForeignKey(Category,related_name='products')
	subcategory = models.ForeignKey(SubCategory,related_name='products',blank=True,null=True)
	subsubcategory = models.ForeignKey(SubSubCategory,related_name='products',blank=True,null=True)
	name = models.CharField(max_length=200, db_index=True)
	slug = models.SlugField(max_length=200, db_index=True)
	image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
	description = models.TextField(blank=True)
	price = models.DecimalField(max_digits=10, decimal_places=2)
	stock = models.PositiveIntegerField()
	available = models.BooleanField(default=True)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	def get_absolute_url(self):
		return reverse('shop:product_detail', args=[self.id, self.slug])
	
	class Meta:
		ordering = ('name',)
		index_together = (('id','slug'),)
	
	def __str__(self):
		return self.name
	
class Computer(Product):
	ram = models.DecimalField(
        ("Screen size"),
        max_digits=4,
        decimal_places=2,
    )

	
# Create your models here.

myshop/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1,21)]

class CartAddProductForm(forms.Form):
	quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
	update = forms.BooleanField(required=False, initial=False, widget= forms.HiddenInput)

myshop/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')

def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
                          initial={'quantity': item['quantity'],
                          'update': True})
    return render(request, 'cart/detail.html', {'cart': cart})

myshop/shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product, SubCategory, SubSubCategory, Computer
from cart.forms import CartAddProductForm

def product_list(request, category_slug=None, subcategory_slug=None, subsubcategory_slug=None):
	category = None
	subcategory = None
	categories = Category.objects.all()
	subcategories = SubCategory.objects.all()
	subsubcategories = SubSubCategory.objects.all()
	products = Product.objects.filter(available=True)
	products_by_price_asc = products.filter(subsubcategory=subsubcategory).order_by('price')
	products_by_price_desc = products.filter(subsubcategory=subsubcategory).order_by('-price')
	if category_slug:
		category = get_object_or_404(Category,slug=category_slug)
		products = products.filter(category=category)
		products_by_price_asc = products.filter(subsubcategory=subsubcategory).order_by('price')
		products_by_price_desc = products.filter(subsubcategory=subsubcategory).order_by('-price')
	return render(request,'shop/product/list.html',{'subcategory':subcategory,'subsubcategory':subsubcategory,'category':category,
													'categories':categories, 'subcategories':subcategories,
													'products':products,
													'products_by_price_asc':products_by_price_asc,'products_by_price_asc':products_by_price_desc,})
# Create your views here.

def product_detail(request, id, slug):
	product = get_object_or_404(Product, id=id, slug=slug, available=True)
	if (get_object_or_404(Product, id=id, slug=slug, available=True).category.name == "Komputery"):
		product = get_object_or_404(Computer, id=id, slug=slug, available=True)
	cart_product_form = CartAddProductForm()
	return render (request,'shop/product/detail.html',{'product':product, 'cart_product_form': cart_product_form})

# Alternatywa
# for n in Computer: czy ten for wogole potrzeby?
# 	if (get_object_or_404(Computer, id=id, slug=slug, available=True)):
# 		product = get_object_or_404(Computer, id=id, slug=slug, available=True)
# for m in Tea:
# 	...
	
	
	
	
	
	

myshop/cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
Koszyk na zakupy
{% endblock %}

{% block content %}
<h1>Koszyk na zakupy</h1>
<table class ="cart">
	<thead>
		<tr>
			<th>Obraz</th>
			<th>Produkt</th>
			<th>Ilość</th>
			<th>Usuń</th>
			<th>Cena jednostkowa</th>
			<th>Kwota</th>
			</tr>
		</thead>
	<tbody>
		{% for item in cart %}
		{% with product=item.product %}
		<tr>
			<td>
				<a href="{{ product.get_absolute_url }}">
					<img src="{% if product.image %} {{ product.image.url }} {% else %} {% static "img/no_image.png" %} {% endif %}">
					</a>
				</td>
			<td>{{ product.name }}</td>
			<td>
				<form action="{% url "cart:cart_add" product.id %}" method="post">
				{{ item.update_quantity_form.quantity }}
				{{ item.update_quantity_form.update }}
				<input type="submit" value="Zmień">
				{% csrf_token %}
				</form>
			</td>
			<td><a href="{% url "cart:cart_remove" product.id %}">Usuń</a></td>
			<td class="num">{{ item.price }} zł</td>
			<td class="num">{{ item.total_price }} zł</td>
			</tr>
		{% endwith %}
		{% endfor %}
		<tr class="total">
			<td>Wartość całkowita</td>
			<td colspan="4"></td>
			<td class="num">{{ cart.get_total_price }} zł</td>
			</tr>
		</tbody>
			</table>
<p class="text-right">
	<a href="{% url "shop:product_list" %}" class="button light">Kontynuuj zakupy</a>
	<a href="#" class="button">Do kasy</a>
	</p>
{% endblock %}
				
				
				
				
				
				
				

myshop/shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<title>{% block title %}Mój sklep{% endblock %}</title>
		<link href="{% static "css/base.css" %}" rel="stylesheet">
	</head>
	<body>
		<div id="header">
			<a href="/" class="logo">Mój sklep</a>
		</div>
		<div id="subheader">
			<div class="cart">
				Koszyk jest pusty.
			</div>
		</div>
		<div id="content">
			{% block content %}
			{% endblock %}
		</div>
	</body>
</html>

myshop/shop/templates/shop/product/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
{% if category %} {{ category.title }} {% else %} Produkty {% endif %}
{% endblock %}

{% block content %}
<div class="product-detail">
	<img src="{% if product.image %} {{ product.image.url }} {% else %} {% static "img/no_image.png" %} {% endif %}">
	<h1> {{ product.name }}</h1>
	<h1> {{ product.ram }}</h1>
	{{ computer.ram }}
	<h2><a href="{{ product.category.get_absolute_url }}"> {{ product.category }} </a></h2>
	<p class="price">{{ product.price }} zł</p>
	<form action="{% url "cart:cart_add" product.id %}" method="post">
		{{ cart_product_form }}
		{% csrf_token %}
		<input type="submit" value="Dodaj do koszyka">
		</form>
	{{ product.description|linebreaks }}
</div>
{% endblock %}

myshop/shop/templates/shop/product/list.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
{% if category %} {{ category.name }} {% else %}Produkty{% endif %}
{% endblock %}

{% block content %}
<div id="sidebar">
	<h3>Kategorie</h3>
	<ul>
		<li {% if not category %}class="selected"{% endif %}>
			<a href="{% url "shop:product_list" %}">Wszystkie</a>
		</li>
		{% for c in categories %}
		<li {% if category.slug == c.slug %}class="selected"{% endif %}>
			
			
			
			
			<a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
			{% for d in subcategories %}
			{% if d.category.name == c.name %}
		<li {% if subcategory.slug == d.slug %}class="selected"{% endif %}>
			<a href="{{ d.get_absolute_url }}">* {{ d.name }}</a>
			
			
			
			{% for f in subsubcategories %}
			{% if f.subcategory.name == d.name %}
		<li {% if subsubcategory.slug == f.slug %}class="selected"{% endif %}>
			<a href="{{ f.get_absolute_url }}">*  *  {{ f.name }}</a>
		</li>
		{% endif %}
		{% endfor %}
			
			
			
		</li>
		{% endif %}
		{% endfor %}
		
		</li>
		{% endfor %}
	
	
	
	
	
		
	</ul>
</div>





<div id="main" class="product-list">
	<h1>{% if category %}{{ category.name }}{% else %}Produkty{% endif %}</h1>
	{% for product in products %}
	<div class="item">
		<a href="{{ product.get_absolute_url }}">
			<img height="200"  src="{% if product.image %} {{ product.image.url }} {% else %} {% static "img/no_image.png" %} {% endif %}">
		</a>
		<a href="{{ product.get_absolute_url }}">{{ product.name }}</a><br>
		{{ product.price }} zł
	</div>
	{% endfor %}
	</div>
{% endblock %}

	
	
	
	
	
	
	
	